# GitHub Sponsors e Doações
# Este arquivo configura os botões de "Sponsor" no GitHub

# GitHub Sponsors
github: ronaldo227

# PayPal
custom: ["https://www.paypal.com/donate/?hosted_button_id=46WJBAZ2X4X6L"]

